# Generated by Django 4.1.4 on 2023-09-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='website_link',
        ),
    ]
